### ISSUE TITLE
rcl_node_init uses wrong return code

### ISSUE THREAD

**Issue by Deric-W** [ros2/rcl#1046]
## Bug report

Operation System: Windows 10
Client library: N/A
Version: Humble

#### Steps to reproduce issue

1. Call `rcl_node_init` with `NULL` as context
2. Check return code

#### Expected behavior

The return code should be `RCL_RET_NOT_INIT` since the context is invalid.

#### Actual behavior

The return code is `RCL_RET_INVALID_ARGUMENT`.

#### Additional information

The [documentation](http://docs.ros.org/en/humble/p/rcl/generated/function_node_8h_1a404531a35e68e71f4900ff48544682b5.html#function-rcl-node-init) suggests that `RCL_RET_NOT_INIT` should be returned since [`rcl_context_is_valid(NULL)`](http://docs.ros.org/en/humble/p/rcl/generated/function_context_8h_1ab6249347bd221d620d7e9432ff2cadd0.html#function-rcl-context-is-valid) returns `false`.
If this is not desirable then the documentation should be updated to mention this.

**Comment by fujitatomoya** [comment]
I think current behavior is correct.

> [RCL_RET_NOT_INIT](http://docs.ros.org/en/humble/p/rcl/generated/define_types_8h_1a61039a0ea73e2c8685572446b237a827.html#types_8h_1a61039a0ea73e2c8685572446b237a827) if the given context is invalid, or

I believe that there is clear difference between `context is invalid` and `argument is invalid`.

- If the context is null via argument, that means argument is invalid, not context. that should return `RCL_RET_INVALID_ARGUMENT`.
- If the context is invalid, arguments are okay, but content of context is not right. that should return `RCL_RET_NOT_INIT`.

**Comment by Deric-W** [comment]
Your reasoning makes sense, I thought `RCL_RET_NOT_INIT` would be returned since the `rcl_{publisher,subscription,client,service}_init` functions behave this way when returning `RCL_RET_NODE_INVALID`.
Would it make sense to mention this in the documentation?

**Comment by Deric-W** [comment]
Implemented in #1066
