### ISSUE TITLE
Remove `localhost_only` option for turtule-J

### ISSUE THREAD

**Issue by fujitatomoya** [ros2/rcl#1070]
## Feature request

`localhost_only` and `ROS_LOCALHOST_ONLY` has been deprecated in Iron Irwini.
For backward compatibility, it still can be effective if `localhost_only` option is enabled to prevail discovery option which is added into Iron Irwini as new feature.
For next-Iron release, this needs to be removed after deprecation period.

#### Feature description

- https://github.com/ros2/rcl/pull/1069, remove all related implementation and test from `rcl` and `rmw`s.
- https://github.com/ros2/ros2_documentation, add explanation and behavior about this. (https://github.com/ros2/ros2_documentation/pull/3596)

#### Implementation considerations

W.I.P

**Comment by ahcorde** [comment]
Done in this PR https://github.com/ros2/rcl/pull/1169 and related ones
