### ISSUE TITLE
does rcl_subscription_get_default_options has data race?

### ISSUE THREAD

**Issue by comicfans** [ros2/rcl#1187]
## Bug report

please note this is only guess.

during checking source code of rcl, I found
[```](https://github.com/ros2/rcl/blob/bfe00f71b7056bb64b27a8d5f5bacefe0564c43e/rcl/src/rcl/subscription.c#L230)
```
 static rcl_subscription_options_t default_options;
  // Must set these after declaration because they are not a compile time constants.
  default_options.qos = rmw_qos_profile_default;
  default_options.allocator = rcl_get_default_allocator();
  default_options.rmw_subscription_options = rmw_get_default_subscription_options();
```

while being called from multi thread, is this data race? recently some data race being found for similar code pattern, please see
https://github.com/ros2/rmw/issues/377
https://github.com/ros2/rcutils/issues/477

and a (maybe) error log  for this
```
 'invalid allocator, at external/ros2_rcl/rcl/src/rcl/subscription.c:219'
rcutils_reset_error() should be called after error handling to avoid this.
invalid allocator, at external/ros2_rcl/rcl/src/rcl/subscription.c:219
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
what():  could not create subscription: invalid allocator, at external/ros2_rcl/rcl/src/rcl/subscription.c:219
```

- Operating System:
  - ubuntu 22.04
- Installation type:
  - build from source
- Version or commit hash:
  - 5.3.7
- DDS implementation:
  - not sure
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
this is only guess

#### Additional information

----

**Comment by fujitatomoya** [comment]
@comicfans if you can review https://github.com/ros2/rcl/pull/1188#, that is really appreciated.
