### ISSUE TITLE
Memory leak from strdup

### ISSUE THREAD

**Issue by jimmy-mcelwain** [ros2/rcl#1198]
Host: YRC1000 running MotoROS2
Client: PC running Ubuntu 22.04
ROS2 version: Humble
Commits: The commit hashes/version used to build MotoROS2 are [available here](https://github.com/Yaskawa-Global/micro_ros_motoplus/blob/humble/target_ws_pkgs.repos)
DDS: FastDDS

I am a contributor to [MotoROS2](https://github.com/Yaskawa-Global/motoros2/). Our implementation allows the controller and client to be disconnected/reconnected repeatedly. Whenever I disconnect the client pc from the host, the memory is freed and everything is shut down, and then everything is re-initialized upon connecting again. However, I noticed a memory leak, 24 bytes per disconnect/reconnect cycle. I eventually traced it to its source and found the leak. 

https://github.com/ros2/rcl/blob/2615b0e8a5e3d9188e50412337e3b306991b05a6/rcl/src/rcl/init.c#L216-L223

The memory allocated in these `strdup` calls is never freed. 

I have a branch on our fork of `micro-ros` [here](https://github.com/Yaskawa-Global/micro_ros_rcl/commit/5aff84885c4b424c9eb160da29b8ed52feb5207f) where I added a single line freeing the memory allocated in that `strdup`, and the memory leak disappeared. There is now no memory lost with a connect/disconnect cycle. 

I noticed the problem in Motoman's own fork of `micro-ros/rcl`, which is somewhat outdated. But looking through the up-to-date upstream repos, the problem is seemingly present in `micro-ros/rcl` as well as here. Not just in humble, but in newer distributions/rolling as well.

I do not know if the spot that I freed the memory is the proper spot to do so. But if I understand correctly, it has not yet been fixed upstream (here) and the proper spot to free the memory is somewhere in this repo.

**Comment by fujitatomoya** [comment]
> which is somewhat outdated. But looking through the up-to-date upstream repos, the problem is seemingly present in micro-ros/rcl as well as here. Not just in humble, but in newer distributions/rolling as well.

did you confirm the there is a memory leak on `ros2/rcl (rolling)`?

it looks like it frees the memory here.

https://github.com/ros2/rcl/blob/2615b0e8a5e3d9188e50412337e3b306991b05a6/rcl/src/rcl/context.c#L135

https://github.com/ros2/rcl/blob/2615b0e8a5e3d9188e50412337e3b306991b05a6/rcl/src/rcl/init_options.c#L138

and i see underlying all rmw tier 1 implementation free the memory for `enclave`.

**Comment by jimmy-mcelwain** [comment]
Sorry for the late response, but thank you. I was unaware that it was the responsibility of the rmw to free that memory. I thought that it was the responsibility of rcl. I am using rmw_microxrcedds. I took a look there, and it seems to me like enclave is not freed if `RCL_MICROROS_COMPLETE_IMPL` is set. I opened up an issue at https://github.com/micro-ROS/rmw_microxrcedds/issues/311.
