### ISSUE TITLE
signatures in some time functions do not match rest of rcl

### ISSUE THREAD

**Issue by wjwwood** [ros2/rcl#121]
For example, `rcl_init_time_source`:

https://github.com/ros2/rcl/blob/93ad1ae4fd05f9952db706f645e610ee377ebb37/rcl/include/rcl/time.h#L118

Should probably be `rcl_time_source_init`, as it is for `rcl_node_init` and `rcl_publisher_init` and so on.

**Comment by wjwwood** [comment]
Also, many of the time functions call out to allocator functions directly like `calloc`:

https://github.com/ros2/rcl/blob/93ad1ae4fd05f9952db706f645e610ee377ebb37/rcl/src/rcl/time.c#L135

They should instead get passed an allocator (perhaps optionally) and use that to allocate memory.

**Comment by mikaelarguedas** [comment]
Should this be put back in ready ? or closed in favor of a new issue with the remaining action item?

**Comment by wjwwood** [comment]
Closed and rest of work put into https://github.com/ros2/rcl/issues/134.
