### ISSUE TITLE
Error in stdatomic_helper.h while compiling with gcc version > 5

### ISSUE THREAD

**Issue by firesurfer** [ros2/rcl#13]
I get the following error while compiling ROS2 with  gcc (Debian 5.3.1-4) 5.3.1 20151219

```
error: missing binary operator before token "("
 #elif defined(__clang__) && defined(__has_feature) && !__has_feature(c_atomic)
```

It compiles when I change line 23 in `stdatomic_helper.h` from

```c++
#elif defined(__clang__) && defined(__has_feature) && !__has_feature(c_atomic)
```

to 

```c++
#elif defined(__clang__) && defined(__has_feature) 
```

on my server with gcc (Debian 4.9.2-10) 4.9.2 it compiles without any errors.

**Comment by wjwwood** [comment]
Interesting, thanks. I guess the evaluation of the conditional doesn't stop when `defined(__has_feature)` is false.

I suppose we can try something like this:

```c++
#elif defined(__clang__) && defined(__has_feature)
#if !__has_feature(c_atomic)
...
#endif
...
```

**Comment by wjwwood** [comment]
@firesurfer if you have a chance, can you try the above and let me know if it works? I don't have a GCC 5 machine handy. If not I can set one up later.

**Comment by firesurfer** [comment]
Hey,
if I change it to:
```c++
#elif defined(__clang__) && defined(__has_feature) 
#if !__has_feature(c_atomic)
// If Clang and no c_atomics (true for some older versions), use the compatability header.
#include "stdatomic_helper/gcc/stdatomic.h"
#endif
```
it compiles.

**Comment by wjwwood** [comment]
I proposed this as a fix: https://github.com/ros2/rcl/pull/14
