### ISSUE TITLE
add tests for rcl_*_is_valid() functions

### ISSUE THREAD

**Issue by wjwwood** [ros2/rcl#150]
Follow up to https://github.com/ros2/rcl/pull/103.

**Comment by mikaelarguedas** [comment]
@allenh1 do you think you will work on this in the near future ?

**Comment by allenh1** [comment]
I certainly could, if needed.

**Comment by mikaelarguedas** [comment]
It looks like you committed to it in https://github.com/ros2/rcl/pull/103#issuecomment-310299057 so it would be great if you can follow up on it :+1: . Otherwise it should be assigned to someone else. The overall goal being to decrease the amount of untested code rather than increasing it

**Comment by allenh1** [comment]
Ok, then. I'll go ahead and assign myself to this one.

**Comment by mikaelarguedas** [comment]
@allenh1 friendly ping

**Comment by allenh1** [comment]
@mikaelarguedas ping received
