### ISSUE TITLE
rcl time uses native calloc

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rcl#154]
found here: https://github.com/ros2/rcl/blob/master/rcl/src/rcl/time.c#L135 and a couple of times later. The functions should provide support for custom allocators.

**Comment by clalancette** [comment]
This is actually a dup of #134 , closing in favor of that one.

**Comment by Karsten1987** [comment]
sorry, just noticed it.

**Comment by clalancette** [comment]
No worries :).
