### ISSUE TITLE
rcl should use test_msgs instead of example_interfaces

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rcl#228]
As example_interfaces are used only for examples and demo and their removal / modification should not impact the test or release of rcl

**Comment by mjcarroll** [comment]
In the cases where a service is used (AddTwoInts), did you want to replace it with an empty service or add a new service to the `test_msgs` package?

**Comment by mikaelarguedas** [comment]
I was thinking of merging https://github.com/ros2/rcl_interfaces/pull/25 that adds a pretty comprehensive set of services
