### ISSUE TITLE
replace uses of reinterpret_cast with static_cast where possible

### ISSUE THREAD

**Issue by wjwwood** [ros2/rcl#269]
See: https://github.com/ros2/rcl/pull/261#discussion_r195932052

**Comment by jhdcs** [comment]
I think I might have replaced a large chunk of the reinterpret_casts. I'm not 100% sure I trust the testing framework to catch any errors, but so far everything seems to be building correctly.

Want me to open a pull request?

**Comment by wjwwood** [comment]
> Want me to open a pull request?

I would default to yes, pull requests can always be declined or refactored, and don't take much to open :)

**Comment by jhdcs** [comment]
Well, I still want to be polite ^_^

**Comment by sloretz** [comment]
Fixed by ros2/rcl#410
