### ISSUE TITLE
services test does not use RMW_IMPLEMENTATION

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/rcl#50]
https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_service.cpp#L31-Lundefined
The name of the services test fixture class should use the RMW_IMPLEMENTATION macro so that the report includes multiple rmw implementations, e.g.

https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_publisher.cpp#L28-L35

**Comment by dirk-thomas** [comment]
The indistinguishable test reports: http://ci.ros2.org/view/nightly/job/nightly_linux_debug/lastCompletedBuild/testReport/(root)/TestServiceFixture/
