### ISSUE TITLE
Perform substitutions when parsing yaml

### ISSUE THREAD

**Issue by mogumbo** [ros2/rcl#527]
In ROS1, yaml files could contain substitutions and it was very useful. I'd like to have this feature in ROS2 as well so that params in my yaml files can point to resources in specific packages like this:
```
my_node:
  ros__parameters:
    data_file: $(find my_package)/data/my_data_file.dat
```

**Comment by wjwwood** [comment]
I'm going to close this in favor of this approach https://github.com/ros2/launch_ros/issues/96, and we can re-open later if we decide different.

**Comment by aravindSwamy94** [comment]
Hi, Is there any update in this, How do we add substitutions in yaml file? This feature was really useful in ROS1 
```
wheel_seperation: $(env WHEEL_SEPERATION)
