### ISSUE TITLE
No documentation for clock types

### ISSUE THREAD

**Issue by nickolai-voyage** [ros2/rcl#552]
## Feature request

Please add documentation for the different clock types, i.e. RCL_STEADY_TIME, RCL_SYSTEM_TIME

#### Feature description
There's no documentation about the differences between these times. I'm guessing that STEADY_TIME is monotonically increasing just based on the name, but it would be really nice to have actual documentation. Something that gets into the doxygen docs would be great.

**Comment by jacobperron** [comment]
Here's the design document describing the clock types: https://design.ros2.org/articles/clock_and_time.html

@nickolai-voyage Would you like to contribute a pull request adding API documentation?

**Comment by fujitatomoya** [comment]
@nickolai-voyage 

is there any reason you picked up RCL_STEADY_TIME, RCL_SYSTEM_TIME in particular?

i guess that https://design.ros2.org/articles/clock_and_time.html should be okay for application since rcl is not exactly the front-end. what do you think?
