### ISSUE TITLE
Add tests checking when a graph guard condition is triggered

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rcl#574]
#### Feature description

There are currently some tests for this ([here](https://github.com/ros2/rcl/blob/2daa408ea46bb2a4305a6221d73ea400e4c02d62/rcl/test/rcl/test_graph.cpp#L1231)), but those are a bit fragile and aren't checking that the graph guard condition is being triggered for all the possible graph changes.

#### Implementation considerations

I imagine the tests looking like:
```
> create another node
  > assert that graph guard condition is triggered within a timeout
> create a publisher
  > assert that graph guard condition is triggered within a timeout
... etc for other possible graph changes
```
instead of using a thread.

Unrelated note: Some of the current graph tests are sleeping with a timeout. Waiting on a graph guard condition trigger in a loop until the desired change is detected would be more reliable.

(edit) Extended the description.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno 

> Feature description
>
> There's currently nothing testing when a graph guard condition is triggered, tests should be added.

I want to make clear the requirement of this issue.  

After checking test in [rcl/test/rcl/test_graph.cpp](https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_graph.cpp), existing test cases are to wait graph guard condition triggering after graph is changed (such as calling rcl_publisher_init()).  
e.g.
test case `test_graph_guard_condition_topics` 

https://github.com/ros2/rcl/blob/2daa408ea46bb2a4305a6221d73ea400e4c02d62/rcl/test/rcl/test_graph.cpp#L1271-L1287 

Calling rcl_publisher_init(), rcl_subscription_init(), rcl_subscription_fini() and rcl_publisher_fini() will affect graph.  That is, `graph guard condition` will be triggered. 

While a graph guard condition is triggered, what test do you want to be added ? e.g. check if publisher is added or deleted ?  

> Implementation considerations
>
> Current graph tests could be refactored to first wait a graph condition is triggered, that will also avoid some flakiness of the current tests.

Current test implementation like as below (such as check_graph_state() ) 
```
loop for try 
    Check status (such as the number of publishers, subscribers)
    If not match expected value 
         add graph guard condition to wait_set
         rcl_wait() //Wait for graph changing 
```

Do you mean rcl_wait() should be done (after graph condition trigger) before check status ?

**Comment by ivanpauno** [comment]
> test case test_graph_guard_condition_topics

Yeah, that test isn't really reliable (those timeouts may be a problem), but that's the basic idea.
Instead of using a thread, I would call functions that have "graph side-effects" and then wait (with a reasonable timeout) to see if the graph guard condition was triggered, sequentially (one at a time).

> While a graph guard condition is triggered, what test do you want to be added ? e.g. check if publisher is added or deleted ?

Anything that has a "graph side-effect" and isn't currently tested is worth adding.

With a "graph side-effect", I mean anything that can change the output of all the functions defined [here](https://github.com/ros2/rcl/blob/master/rcl/include/rcl/graph.h) and [publisher_count](https://github.com/ros2/rcl/blob/8bcada7b884693644d7ba2e3bd2c22fd9541eba7/rcl/include/rcl/subscription.h#L568)/[subscription_count](https://github.com/ros2/rcl/blob/8bcada7b884693644d7ba2e3bd2c22fd9541eba7/rcl/include/rcl/publisher.h#L603) functions.


> Do you mean rcl_wait() should be done (after graph condition trigger) before check status ?

I don't get the question.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno 

Got it.  Thanks for your explanation.   
I or @Ada-King will continue to handle this issue. 

>> Do you mean rcl_wait() should be done (after graph condition trigger) before check status ?
>
>I don't get the question.

You can ignore this unclear question.

**Comment by Barry-Xu-2018** [comment]
@ivanpauno 

Please review #811

**Comment by fujitatomoya** [comment]
@ivanpauno @Barry-Xu-2018 

can we close this?
