### ISSUE TITLE
Setup code documentation generation

### ISSUE THREAD

**Issue by wjwwood** [ros2/rcl#6]
Temporarily until we have a general solution, so that people can generate and browse the documentation we have so far on this package.

The other motivation for setting this up is to resolve issues like this one: https://github.com/ros2/rcl/pull/5#discussion_r46497258

**Comment by clalancette** [comment]
@wjwwood Should we leave this open?  Sorry, I'm not sure exactly what this ticket is referring to.

**Comment by wjwwood** [comment]
This is a task to generate the API documentation for this package, which we've since done, at least in a temporary fashion:

http://docs.ros2.org/beta2/api/rcl/index.html
