### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ros2/rcl#602]
This issue tracks the progression of packages in `rcl` that have been deemed necessary for Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/rep-2004/rep-2004.rst). 

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- rcl
- rcl_action
- rcl_lifecycle
- rcl_yaml_param_parser

# Progress common to all packages:
* [x] Version Policy
    - `semver` according to the recommendation for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#versioning).
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Quality Declaration document for each package
* [x] Vulnerability Disclosure Policy
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Checked with ament_lint_common

# Progress of specific packages
## rcl

Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - rmw (QL 4)
  - rcl_interfaces (QL 4)
  - rcl_logging_spdlog (QL 4)
  - rcl_yaml_param_parser (QL 4)
  - rcutils (QL 2)
  - rmw_implementation (QL 4)
  - rosidl_runtime_c (QL 4)
  - tracetools (QL 2)
* [x] Non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
* [ ] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

## rcl_action
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - rmw (QL 4)
  - rcutils (QL 2)
  - rosidl_runtime_c (QL 4)
  - action_msgs (QL 4)
* [x] Non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

## rcl_lifecycle
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - rmw (QL 4)
  - rcl (QL 4)
  - lifecycle_msgs (QL 4)
  - rosidl_runtime_c (QL 4)
* [x] Non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
* [ ] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

## rcl_yaml_param_parser
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
  - libyaml_vendor (QL 4)
  - rcutils (QL 2)
* [x] Non-ROS dependencies are equivalent level 1
  - None

Testing:
* [x] Must have system tests which cover all items in the "feature" documentation
* [x] Must have system, integration, and/or unit tests which cover all of the public API
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [x] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

**Comment by jacobperron** [comment]
FYI, we now have a 1.0.0 release: https://github.com/ros/rosdistro/pull/24843

**Comment by chapulina** [comment]
All packages reached level 1 :tada: https://github.com/ros2/rcl/pull/866/
