### ISSUE TITLE
Wrong INTERFACE_LINK_LIBRARIES in rcl_yaml_param_parser

### ISSUE THREAD

**Issue by alsora** [ros2/rcl#638]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - master of 1st May 2020

#### Steps to reproduce issue

This issue is probably related to https://github.com/ros2/ros2/issues/904

I built ROS 2 from sources, then I moved the compiled workspace to a new directory
```
colcon build --cmake-args --no-warn-unused-cli
mv /root/ros2_ws/install /home/asoragna/ros2_x86
```

I source the environment specifying the new prefix
```
COLCON_CURRENT_PREFIX=/home/asoragna/ros2_x86 source /home/asoragna/ros2_x86/setup.sh
```

In a separate CMake project:
```
find_package(rcl_yaml_param_parser CONFIG)
get_target_property(_libs rcl_yaml_param_parser::rcl_yaml_param_parser INTERFACE_LINK_LIBRARIES)
message(WARNING "LIBS: ${_libs}")
```

#### Expected behavior

I would expect to find valid targets (since now ROS 2 moved to export targets).

#### Actual behavior

```
  LIBS:
  rcutils::rcutils;/root/ros2_ws/install/libyaml_vendor/lib/libyaml.so;yaml
```

There is an absolute path from the original location where ROS 2 has been compiled.
Note that the path is actually not needed at all, as `yaml` is also there.
However its presence causes errors as CMake tries to check that file.

**Comment by dirk-thomas** [comment]
This is being addressed by ros2/libyaml_vendor#16.
