### ISSUE TITLE
Improve error messages in rcl_lifecycle

### ISSUE THREAD

**Issue by ahcorde** [ros2/rcl#655]
`rcl_lifecycle` is using only two kind of errors: `RCL_RET_ERROR` and `RCL_RET_OK`. There is room for improvement here. We should add a more accurate error message.

**Comment by brawner** [comment]
Thanks for opening the issue @ahcorde! For reference, this follows up #649, where we decided to hold off on changing return codes until after the foxy release

**Comment by llapx** [comment]
I just modify the headers files, mainly for document, if it's OK, I will push the code, thanks!

**Comment by ahcorde** [comment]
Closed via https://github.com/ros2/rcl/pull/742
