### ISSUE TITLE
Missing to call rcl_lifecycle_transition_fini() and rcl_node_fini() in lifecycle test

### ISSUE THREAD

**Issue by Barry-Xu-2018** [ros2/rcl#713]
## Bug report

**Required Info:**

- Operating System:
    All
- Installation type:
  Binaries and From source
- Version or commit hash:
   master branch (0de31d04830)
- DDS implementation:
   Any

#### Steps to reproduce issue

Check codes 

Part 1

https://github.com/ros2/rcl/blob/944068f3d99d6a4b1130fd62e38c69b96f0e759e/rcl_lifecycle/test/test_rcl_lifecycle.cpp#L134-L143

Part 2
https://github.com/ros2/rcl/blob/944068f3d99d6a4b1130fd62e38c69b96f0e759e/rcl_lifecycle/test/test_rcl_lifecycle.cpp#L193-L199

Part 3
https://github.com/ros2/rcl/blob/944068f3d99d6a4b1130fd62e38c69b96f0e759e/rcl_lifecycle/test/test_rcl_lifecycle.cpp#L352-L358

#### Expected behavior

- Correctly recycling resource
    - In part 1, once rcl_lifecycle_transition_init() is called successfully, rcl_lifecycle_transition_fini() should be called for recycling resource.
    - In part 2 and part 3,  if call rcl_node_init(), while exiting test, rcl_node_fini() should be called for recycling resource.
#### Actual behavior

- rcl_lifecycle_transition_fini() isn't called after rcl_lifecycle_transition_init() is called successfully.

- While exiting test, rcl_node_fini() isn't called.

**Comment by Karsten1987** [comment]
Thanks for reporting this issue. I think this goes in hand with what we see at the nightly builds as well:
```
05:32:22 1: [ RUN      ] TestDefaultStateMachine.default_init
05:32:22 1: 
05:32:22 1: >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
05:32:22 1: This error state is being overwritten:
05:32:22 1: 
05:32:22 1:   'invalid allocator, at /home/jenkins-agent/workspace/nightly_linux_release/ws/src/ros2/rcl/rcl_lifecycle/src/transition_map.c:91'
05:32:22 1: 
05:32:22 1: with this new error message:
05:32:22 1: 
05:32:22 1:   'can't free transition map, no allocator given
05:32:22 1: , at /home/jenkins-agent/workspace/nightly_linux_release/ws/src/ros2/rcl/rcl_lifecycle/src/transition_map.c:57'
05:32:22 1: 
05:32:22 1: rcutils_reset_error() should be called after error handling to avoid this.
05:32:22 1: <<<
05:32:22 1: [       OK ] TestDefaultStateMachine.default_init (1 ms)
```

do you mind opening a pull request for this?

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 

could you change the title? there are double `call` in the head of the title.

**Comment by Barry-Xu-2018** [comment]
@Karsten1987 

> do you mind opening a pull request for this?

Yes. I will fixing it.  
Please assign this issue to me.

**Comment by Barry-Xu-2018** [comment]
@fujitatomoya 

> could you change the title? there are double call in the head of the title.

OK. I worry about the title is too long. So I just describe one problem in title.

**Comment by Barry-Xu-2018** [comment]
@Karsten1987 

> do you mind opening a pull request for this?
>
> Above log doesn't affect test.
> This isn't a bug. Do you want to not show these error message ?

I find the cause. 
It is bug in test codes. I will fix it.

**Comment by Barry-Xu-2018** [comment]
@Karsten1987 

I have updated above comments to explain the problem reported by you (https://github.com/ros2/rcl/issues/713#issuecomment-657746623).  
Please take a look.

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 @Karsten1987 

> https://github.com/ros2/rcl/issues/713#issuecomment-657746623

Since the overwrite condition is notified, I do not see this is a problem but status.

> fail_error_message, fini_error

I think failure of registering transitions and memory leak is different, current code cannot support failure w/o memory leak case. And to support the memory leak case, `rcl_copy_error_string` backed with __rcutils_copy_string would be introduced?

**Comment by Barry-Xu-2018** [comment]
@fujitatomoya 

> Since the overwrite condition is notified, I do not see this is a problem but status.

Yes. It should be warning on error state to be overwritten.

> I think failure of registering transitions and memory leak is different, current code cannot support failure w/o memory leak case. And to support the memory leak case, rcl_copy_error_string backed with __rcutils_copy_string would be introduced?

About  `memory leak` mentioned by you,  https://github.com/ros2/rcl/issues/713#issuecomment-657746623 doesn't lead memory leak.   
```c
       fini_error = rcl_get_error_string().str; 
       rcl_reset_error();
     }

       RCL_SET_ERROR_MSG_WITH_FORMAT_STRING(
      "Freeing transition map failed while handling a previous error. Leaking memory!"
      "\nOriginal error:\n\t%s\nError encountered in rcl_lifecycle_transition_map_fini():\n\t%s\n",
      fail_error_message, fini_error);
```
After rclreset_error(), fini_error point to empty string. Error message has been reset.  
This leads `RCL_SET_ERROR_MSG_WITH_FORMAT_STRING` output empty error message.

**Comment by fujitatomoya** [comment]
> About memory leak mentioned by you, #713 (comment) doesn't lead memory leak.

i wasn't clear on this, my bad. i do understand what you mean. i was mentioning the "Freeing transition map failed while handling a previous error. Leaking memory!" message.

**Comment by Barry-Xu-2018** [comment]
> i wasn't clear on this, my bad. i do understand what you mean. i was mentioning the "Freeing transition map failed while handling a previous error. Leaking memory!" message.

Got it. Even if this error said memory leak, actually failure is because `allocator` is set to nullptr for test.  
transition map isn't initialized successfully since `allocator` is nullptr. So there is no memory leak.

**Comment by Barry-Xu-2018** [comment]
@Karsten1987 

About https://github.com/ros2/rcl/issues/713#issuecomment-657746623, the solution mentioned at  https://github.com/ros2/rcl/issues/713#issuecomment-658043362 has problem.  

Below is updated solution.  
Please check it.  
https://github.com/Barry-Xu-2018/rcl/commit/a8e848736b0df5e794fdf43c561da927463cf6e5

**Comment by Barry-Xu-2018** [comment]
@Karsten1987 

Since fixing (https://github.com/ros2/rcl/pull/715) was merged, I close this issue.
