### ISSUE TITLE
Loaned functions returning rcl_ret_t use rmw_ret_t

### ISSUE THREAD

**Issue by Blast545** [ros2/rcl#735]
Loaned functions as `rcl_borrow_loaned_message`:

```
rcl_ret_t
rcl_borrow_loaned_message(
  const rcl_publisher_t * publisher,
  const rosidl_message_type_support_t * type_support,
  void ** ros_message)
{
  if (!rcl_publisher_is_valid(publisher)) {
    return RCL_RET_PUBLISHER_INVALID;  // error already set
  }
  return rmw_borrow_loaned_message(publisher->impl->rmw_handle, type_support, ros_message);
}
```

Make a call to a `rmw` function and the result is returned as a `rcl_ret_t`. I think for those it's needed an additional `rcl_convert_rmw_ret_to_rcl_ret` call. Let me know your thoughts and I'll open a PR accordingly.

**Comment by clalancette** [comment]
> I think for those it's needed an additional `rcl_convert_rmw_ret_to_rcl_ret` call. Let me know your thoughts and I'll open a PR accordingly.

Yep, looks like it.  Seems reasonable to me to open a PR to fix that.
