### ISSUE TITLE
test_client failing with Connext

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rcl#767]
See https://github.com/osrf/buildfarmer/issues/84#issuecomment-681015489

Test `rcl/test_client` failing with Connext on Linux and macOS:

* ci.ros2.org
  * https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1669/testReport/
  * https://ci.ros2.org/view/nightly/job/nightly_linux_release/1652/testReport/
  * https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1749/testReport/
  * https://ci.ros2.org/view/nightly/job/nightly_osx_release/1763/testReport/
* build.ros2.org
  * http://build.ros2.org/view/Rci/job/Rci__nightly-debug_ubuntu_focal_amd64/58/testReport/
  * http://build.ros2.org/view/Rci/job/Rci__nightly-release_ubuntu_focal_amd64/58/testReport/

I would suspect #727 to have caused this regression which also didn't run the tests with Connext.

**Comment by brawner** [comment]
Addressed over at https://github.com/ros2/rosidl_typesupport_connext/pull/60
