### ISSUE TITLE
test_rcl_lifecycle failing with cyclonedds

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rcl#787]
Example failure: http://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_focal_amd64/

I think this error output is the problem:

> Not all nodes were finished before finishing the context

**Comment by ivanpauno** [comment]
@brawner this seem to have been introduced in https://github.com/ros2/rcl/pull/731, is that the case?

**Comment by ivanpauno** [comment]
FYI @azeey as buildfarmer

**Comment by brawner** [comment]
Thanks for bringing this to my attention. #731 likely introduced the test that uncovered this bug. We've been seeing this happen with cyclone and connext, where additional bugs surface after the fault injection PRs are merged. I'll take a look at it and figure out a bug fix

**Comment by brawner** [comment]
> additional bugs surface after the fault injection PRs are merged

That was pure hubris. This test failure was all my doing and there were no additional bugs to fix in rmw_cyclonedds_cpp. It makes me wonder why calling `rcl_shutdown` without calling `rcl_node_fini` worked with the other rmws.

**Comment by ivanpauno** [comment]
> It makes me wonder why calling rcl_shutdown without calling rcl_node_fini worked with the other rmws

I think that calling destruction functions in the correct order is UB currently (to give a different example, destroying a publisher after destroying the "parent" node).
In some rmw implementations, doing it in the opposite order might be ok, but in some others it might fail.
