### ISSUE TITLE
rcl_actions test_graph failing on Windows with Connext flaky

### ISSUE THREAD

**Issue by tfoote** [ros2/rcl#897]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - nightly CI
- Version or commit hash:
  - nightly
- DDS implementation:
  - rmw_connext
- Client library (if applicable):
  - rcl_action

#### Steps to reproduce issue

Nightly Win Release
https://ci.ros2.org/job/nightly_win_rel/1866/testReport/(root)/projectroot/test_graph__rmw_connext_cpp/history/
![Screenshot from 2021-03-08 15-14-56](https://user-images.githubusercontent.com/447804/110394633-9d85cd80-8021-11eb-91f7-d042065bc37e.png)

Nightly Win Repeated
https://ci.ros2.org/job/nightly_win_rep/2176/testReport/(root)/projectroot/test_graph__rmw_connext_cpp/history/
![Screenshot from 2021-03-08 15-17-49](https://user-images.githubusercontent.com/447804/110394624-9959b000-8021-11eb-86ef-9c93bdfa0585.png)

These jobs appear to have been flaky and are now getting more common in failing. 

#### Expected behavior

Tests Pass reliably

#### Actual behavior

One or more tests in this suite fail. 

Observed failures include:
* test_action_get_names_and_types
* get_names_and_types_maybe_fail
* rcl_get_client_names_and_types_by_node_maybe_fail
* rcl_get_server_names_and_types_by_node_maybe_fail
* action_client_init_maybe_fail
* test_action_get_client_names_and_types_by_node

**Comment by clalancette** [comment]
We've switched to the new `rmw_connextdds` now, and we haven't seen these particular failures so far.  Given that it is an entirely different implementation, I'm going to go ahead and close this issue.  If new issues come up with `rmw_connextdds`, we'll deal with them separately.
