### ISSUE TITLE
Problems with arguments in rcl_timer_exchange_period api

### ISSUE THREAD

**Issue by NoyZuberi** [ros2/rcl#967]
In function rcl_timer_exchange_period I saw that the arguments that we send are (const rcl_timer_t * timer, int64_t new_period, int64_t * old_period)  - the period arguments are int64
But in its implementation you use it as uint64 (*old_period = rcutils_atomic_exchange_uint64_t(&timer->impl->period, new_period);).

Every time we call this function we get warning failures, we think it might be related to this issue.

Is this a known issue? Or there are might be some assumptions that we need to know before calling this function?

Thanks.

**Comment by fujitatomoya** [comment]
thanks for the issue. i believe this is bug. the followings are my thoughts.

- `period` must/will be non-negative, and this is checked via `rcl_timer_init`.
- `rcl_timer_get_period` has the same problem with `rcl_timer_exchange_period`. `rcutils_atomic_exchange_int64_t` should be used for both of them.
- it should check `new_period` in `rcl_timer_exchange_period` if it is negative and return `RCL_RET_INVALID_ARGUMENT` too.

@ivanpauno @hidmic @sloretz what do you think?
